# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				bee = true
				axolotl = true
				donkey = true
				cow = true
				tropical_fish = true
				fox = true
				chest_minecart = true
				pig = true
				slime = true
				skeleton = true
				iron_golem = true
				bat = true
				frog = true
				cat = true
				rabbit = true
				zombie = true
				armor_stand = true
				drowned = true
				sheep = true
				player = true
				dolphin = true
				pufferfish = true
				item = true
				villager = true
				wolf = true
				salmon = true
				zombie_villager = true
				tnt_minecart = true
				horse = true
				cave_spider = true
				glow_squid = true
				witch = true
				cod = true
				glow_item_frame = false
				squid = true
				spider = true
				creeper = true
				enderman = true
				llama = true
				goat = true
				parrot = true
				turtle = true
				ocelot = true
				illusioner = true
				item_frame = true
				magma_cube = true
				potion = true
				wandering_trader = true
				wither_skeleton = true
				painting = true
				arrow = true
				husk = true
				area_effect_cloud = true
				pillager = true
				polar_bear = true
				vindicator = true
				evoker = true
				experience_orb = true
				mooshroom = true
				stray = true
				allay = true
				guardian = true
				panda = true
				skeleton_horse = true
				ravager = true
				piglin = true
				piglin_brute = true
				hoglin = true
				strider = true
				zombified_piglin = true
				ghast = true
				blaze = true
				phantom = true
				vex = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.biomeswevegone]
				man_o_war = true
				oddion = true
				pumpkin_warden = true

			[light_sources.settings.entities.wildlife]
				lark = true
				king_snake = true
				snail = true
				hedgehog = true
				sanddollar = true
				horseshoecrab = true
				hermitcrab = true
				seaurchin = true
				june_beetle = true
				tiger_butterfly = true
				sunflowerbeetle = true
				grass_snake = true
				monarch_butterfly = true
				ladybug = true
				spider = true
				stickbug = true
				dragonfly = true
				glow_jellyfish = true
				anglerfish = true
				clam = true
				starfish = true
				staghorn_beetle = true
				crab = true
				possum = true
				spicebush_butterfly = true
				robin = true
				sparrow = true
				porcupine = true
				phoebe = true
				cricket = true
				ferret = true
				koi = true
				bluegill = true
				goldfish = true
				meadowlark = true
				catfish = true
				ant = true
				glasswing_butterfly = true
				oriole = true
				armadillo = true
				flycatcher = true
				chameleon = true
				anteater = true
				gecko = true
				python = true
				alligator = true
				milk_snake = true
				bluebird = true
				hamster = true
				prawn = true
				bettafish = true
				rainbow_trout = true
				stingray = true
				hammerhead_shark = true
				mantaray = true
				seahorse = true
				shrimp = true
				jellyfish = true
				goldfinch = true
				wren = true
				rhino_beetle = true
				iguana = true
				badger = true
				white_eye = true
				towhee = true
				cottonbird = true
				morpho_butterfly = true
				boar = true
				deer = true
				beaver = true
				swallow = true

			[light_sources.settings.entities.smallships]
				brigg = true

			[light_sources.settings.entities.mythicmounts]
				geckotoalizard = true
				dragon = true
				griffon = true
				firebird = true
				colelytra = true
				acencia = true
				courierbird = true
				direwolf = true
				moth = true

			[light_sources.settings.entities.spell_engine]
				spell_area_effect = true
				spell_projectile = true

			[light_sources.settings.entities.graveyard]
				skeleton_creeper = true
				corrupted_vindicator = true
				acolyte = true
				corrupted_pillager = true
				nameless_hanged = true
				nightmare = true
				ghoul = true
				revenant = true

			[light_sources.settings.entities.aquamirae]
				spinefish = true
				anglerfish = true
				golden_moth = true
				maw = true
				tortured_soul = true
				eel = true

			[light_sources.settings.entities.obscure_api]
				texture_fx = true

			[light_sources.settings.entities.soulsweapons]
				silver_bullet_entity = true
				cannonball_entity_type = true
				dark_sorcerer = true
				evil_forlorn = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.create]
				super_glue = true

