name: Create and publish release

on:
  push:
    tags:
    - v*

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Get mrpack file
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Sunnie's RPG Tech 1.20.1.mrpack
          sparse-checkout-cone-mode: false
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" "${GITHUB_WORKSPACE}/Sunnie's RPG Tech 1.20.1.mrpack" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag}" \
              --generate-notes

  publish:
    name: Publish to Modrinth
    needs: release
    runs-on: ubuntu-latest
    steps:
    - name: Publish to Modrinth
      uses: cloudnode-pro/modrinth-publish@1.0.0
      with:
        token: ${{ secrets.MODRINTH_TOKEN }}
        project: hEe6vPdd
        file: target/Sunnie's RPG Tech 1.20.1.mrpack
        changelog: ${{ github.event.release.body }}
        loaders: fabric
        api-domain: api.modrinth.com
