name: Publish to Modrinth

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: Publish to Modrinth
    runs-on: ubuntu-latest
    steps:
    - name: Download latest release
      uses: robinraju/release-downloader@v1
      with:
        latest: true
        fileName: 'Sunnie.s.RPG.Tech.1.20.1.mrpack'
    - name: Publish to Modrinth
      uses: dsx137/modrinth-release-action@main
      env:
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      with:
        name: ${{ github.ref_name }}
        project_id: hEe6vPdd
        loaders: fabric
        game_versions: 1.20.1
        version_number: ${{ github.ref_name }}
        changelog: ${{ github.event.release.body }}
        files: ${{ github.workspace }}/Sunnie.s.RPG.Tech.1.20.1.mrpack
