name: Publish to Modrinth

on:
  - release:
    types: [ published ]

jobs:
  publish:
    name: Publish to Modrinth
    runs-on: ubuntu-latest
    steps:
    - name: Download latest release
      uses: robinraju/release-downloader@v1
      with:
        latest: true
        fileName: 'Sunnie.s.RPG.Tech.1.20.1.mrpack'
        
    - name: Upload to Modrinth
      uses: RubixDev/modrinth-upload@v1
      with:
        token: ${{ secrets.MODRINTH_TOKEN }}
        file_path: ./Sunnie.s.RPG.Tech.1.20.1.mrpack
        name: Sunnie's RPG Tech 1.20.1
        version: ${{ github.event.release.tag_name }}
        changelog: ${{ github.event.release.body }}
        game_versions: 1.20.1
        loaders: fabric
        featured: true
        project_id: hEe6vPdd
